# Generated by Django 5.2 on 2025-05-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorrecursos',
            name='correo',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestorrecursos',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripcion', max_length=500),
        ),
        migrations.AddField(
            model_name='gestorrecursos',
            name='direccion',
            field=models.CharField(blank=True, default='Sin direccion', max_length=255),
        ),
        migrations.AlterField(
            model_name='gestorrecursos',
            name='telefono',
            field=models.CharField(blank=True, default='Sin telefono', max_length=15),
        ),
    ]
