# Generated by Django 5.2 on 2025-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0002_gestorrecursos_correo_gestorrecursos_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestorrecursos',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
