# Generated by Django 5.2 on 2025-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0003_alter_gestorrecursos_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestorrecursos',
            name='correo',
            field=models.EmailField(blank=True, default='Sin correo', max_length=254, unique=True),
        ),
    ]
