# Generated by Django 5.2 on 2025-05-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0004_alter_gestorrecursos_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion', models.TextField(blank=True, default='Sin descripcion', max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recursos/')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('herramienta', 'Herramienta'), ('equipo', 'Equipo'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorRecursos.gestorrecursos')),
            ],
            options={
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
