# Generated by Django 5.2 on 2025-06-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0005_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='cantidad',
        ),
    ]
