# Generated by Django 5.2 on 2025-06-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0007_remove_asignacionrecursos_escala_and_more'),
        ('GestorRecursos', '0006_remove_recurso_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='puertos_disponibles',
            field=models.ManyToManyField(blank=True, related_name='recursos_disponibles', to='GestorNavios.puerto'),
        ),
    ]
