# Generated by Django 5.2 on 2025-06-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0007_recurso_puertos_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.JSONField(blank=True, default={'productos': {'Herramientas y Equipamiento': ['Herramientas manuales: Martillos, Llaves, Destornilladores, Alicates', 'Herramientas eléctricas: Taladros, Amoladoras, Sierras', 'Equipos de medición: Multímetros, Calibradores, Medidores de presión'], 'Repuestos y Suministros Técnicos': ['Componentes mecánicos: Rodamientos, Correas, Juntas', 'Componentes eléctricos: Fusibles, Bombillas LED, Cables, Baterías', 'Filtros: Aceite, Combustible, Aire', 'Mangueras y conexiones']}, 'servicios': {'Mantenimiento y Reparación': ['Reparación de motores', 'Reparación eléctrica', 'Soldadura', 'Reparación de sistemas hidráulicos', 'Limpieza de casco o hélice']}}),
        ),
    ]
