# Generated by Django 5.2 on 2025-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0008_alter_recurso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('material', 'Material'), ('herramienta', 'Herramienta'), ('equipo', 'Equipo'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
