# Generated by Django 5.2 on 2025-06-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorRecursos', '0009_alter_recurso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='subtipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
