# Generated by Django 5.2 on 2025-05-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0003_alter_gestornavios_user'),
        ('GestorRecursos', '0005_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arribo', models.DateTimeField()),
                ('fecha_zarpe', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='Navio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoNumero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('manga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('carga', 'Carga'), ('pasajeros', 'Pasajeros'), ('pesquero', 'Pesquero'), ('militar', 'Militar'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, default='Sin ubicacion', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorRecursos.recurso')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorNavios.escala')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='navio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorNavios.navio'),
        ),
        migrations.AddField(
            model_name='escala',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorNavios.puerto'),
        ),
    ]
