# Generated by Django 5.2.1 on 2025-05-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0004_escala_navio_puerto_asignacionrecursos_escala_navio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navio',
            name='tipo',
        ),
    ]
