# Generated by Django 5.2.1 on 2025-05-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0005_remove_navio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navio',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('esperando_escala', 'Esperando asignación de escala'), ('esperando_recursos', 'Esperando asignación de recursos'), ('completo', 'Asignación completa'), ('inactivo', 'Inactivo')], default='inactivo', max_length=50),
        ),
    ]
