# Generated by Django 5.2 on 2025-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0006_alter_navio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionrecursos',
            name='escala',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='puerto',
        ),
        migrations.CreateModel(
            name='EscalaPuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorNavios.escala')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorNavios.puerto')),
            ],
            options={
                'verbose_name_plural': 'Escalas y Puertos',
            },
        ),
        migrations.AddField(
            model_name='asignacionrecursos',
            name='escala_puerto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestorNavios.escalapuerto'),
        ),
        migrations.AddField(
            model_name='escala',
            name='puerto',
            field=models.ManyToManyField(through='GestorNavios.EscalaPuerto', to='GestorNavios.puerto'),
        ),
    ]
