# Generated by Django 5.2.1 on 2025-06-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0008_auto_20250605_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navio',
            name='estado',
            field=models.CharField(choices=[('completo', 'Asignación completa'), ('inactivo', 'Inactivo')], default='inactivo', max_length=50),
        ),
    ]
