# Generated by Django 5.2 on 2025-06-07 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0008_auto_20250605_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='fecha_arribo',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='fecha_zarpe',
        ),
        migrations.AddField(
            model_name='escalapuerto',
            name='fecha_arribo',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='escalapuerto',
            name='fecha_zarpe',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='navio',
            name='estado',
            field=models.CharField(choices=[('completo', 'Asignación completa'), ('inactivo', 'Inactivo')], default='inactivo', max_length=50),
        ),
    ]
