# Generated by Django 5.2 on 2025-06-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0009_alter_navio_estado'),
        ('GestorNavios', '0009_remove_escala_fecha_arribo_remove_escala_fecha_zarpe_and_more'),
    ]

    operations = [
    ]
