# Generated by Django 5.2.1 on 2025-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0010_merge_20250606_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='nombre',
            field=models.CharField(default='Escala sin nombre', max_length=100),
        ),
    ]
