# Generated by Django 5.2.1 on 2025-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorNavios', '0011_escala_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
